name: Build and Auto Merge

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build documentation
              run: npm run docs:build

    automerge:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'

        steps:
            - uses: actions/checkout@v3

            - name: Auto-merge
              uses: pascalgn/automerge-action@v0.15.6
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  MERGE_LABELS: ""
                  MERGE_METHOD: "merge"
                  MERGE_COMMIT_MESSAGE: "Auto-merge PR #{pullRequest.number}: {pullRequest.title}"
                  MERGE_RETRY_SLEEP: "60000"
                  MERGE_RETRIES: "6"
